name: operator_microbenchmark

on:
  push:
    tags:
      - ciflow/op-benchmark/*
  workflow_dispatch:
  schedule:
    # Run at 06:00 UTC every Sunday
    - cron: 0 6 * * 0

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  opmicrobenchmark-build:
    if: github.repository_owner == 'pytorch'
    name: opmicrobenchmark-build
    uses: ./.github/workflows/_linux-build.yml
    with:
      # Use a bigger runner here because CUDA_ARCH 9.0 is only built for H100
      # or newer GPUs, so it doesn't benefit much from existing compiler cache
      # from trunk. Also use a memory-intensive runner here because memory is
      # usually the bottleneck
      runner: linux.12xlarge.memory
      build-environment: linux-jammy-cuda12.8-py3.10-gcc9-sm80
      docker-image-name: ci-image:pytorch-linux-jammy-cuda12.8-cudnn9-py3-gcc11
      cuda-arch-list: '8.0 9.0'
      test-matrix: '{"include": [{"config": "operator_microbenchmark_test", "shard": 1, "num_shards": 1, "runner": "linux.aws.h100", "op_benchmark_tests": "matmul mm add bmm", "extra_flags": "--use-compile"}, {"config": "operator_microbenchmark_test", "shard": 1, "num_shards": 1, "runner": "linux.aws.h100", "op_benchmark_tests": "matmul mm add bmm"}, {"config": "operator_microbenchmark_test", "shard": 1, "num_shards": 1, "runner": "linux.aws.a100", "op_benchmark_tests": "matmul mm add bmm", "extra_flags": "--use-compile"}, {"config": "operator_microbenchmark_test", "shard": 1, "num_shards": 1, "runner": "linux.aws.a100", "op_benchmark_tests": "matmul mm add bmm"}]}'
    secrets: inherit

  opmicrobenchmark-test:
    name: opmicrobenchmark-test
    uses: ./.github/workflows/_linux-test.yml
    needs: opmicrobenchmark-build
    with:
      build-environment: linux-jammy-cuda12.8-py3.10-gcc9-sm80
      docker-image: ${{ needs.opmicrobenchmark-build.outputs.docker-image }}
      test-matrix: ${{ needs.opmicrobenchmark-build.outputs.test-matrix }}
    secrets: inherit
